version: "3"
services:

  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tourist_advice_db
    restart: always
#    networks:
#      - postgres
#    volumes:
#      - ./db-data:/var/lib/postgresql/data
#
#  ngrok:
#    image: wernight/ngrok
#    container_name: ngrok
#    ports:
#      - "4045:4040"
#    environment:
#      - NGROK_PROTOCOL=http
#      - NGROK_PORT="host.docker.internal:8083"
#    networks:
#      - ngrok


  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - telegram-bot
    environment:
      - DOMAIN=telegram-bot
      - PORT=8081

  #    environment:
#      NGROK_PORT: http://localhost:8083
#    ports:
#      - "4040:4040"

  telegram-bot:
    build: ./telegram-bot
    container_name: telegram-bot
#    ports:
#      - 8083:8080
    restart: always
    depends_on:
      - db
#      - ngrok
#    networks:
#      - ngrok
#      - postgres

  telegram-bot-rest:
    build: ./telegram-bot-rest
    container_name: telegram-bot-rest
    #    ports:
    #      - 8083:8080
    restart: always
    depends_on:
      - db
  #      - ngrok
  #    networks:
  #      - ngrok
  #      - postgres

  frontend:
    build:
      context:  ./frontend
      dockerfile: Dockerfile
      args:
        PROXY_URL: http://telegram-bot-rest:8082
    container_name: frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - telegram-bot-rest

#networks:
#  ngrok:
#  postgres:
