version: "3"
services:

  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tourist_advice_db
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data

  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - telegram-bot
    environment:
      - DOMAIN=telegram-bot
      - PORT=8081

  telegram-bot:
    build: ./telegram-bot
    container_name: telegram-bot
    restart: always
    depends_on:
      - db

  telegram-bot-rest:
    build: ./telegram-bot-rest
    container_name: telegram-bot-rest
    restart: always
    depends_on:
      - db

  frontend:
    build:
      context:  ./frontend
      dockerfile: Dockerfile
      args:
        PROXY_URL: http://telegram-bot-rest:8082
    container_name: frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - telegram-bot-rest

volumes:
  db_volume:
