version: "3"
services:

  db:
    image: postgres
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tourist_advice_db
    restart: always
#    networks:
#      - postgres
#    volumes:
#      - ./db-data:/var/lib/postgresql/data
#
#  ngrok:
#    image: wernight/ngrok
#    container_name: ngrok
#    ports:
#      - "4045:4040"
#    environment:
#      - NGROK_PROTOCOL=http
#      - NGROK_PORT="host.docker.internal:8083"
#    networks:
#      - ngrok


  ngrok:
    image: shkoliar/ngrok:latest
    ports:
      - 4551:4551
    links:
      - backend
    environment:
      - DOMAIN=backend
      - PORT=8080

  #    environment:
#      NGROK_PORT: http://localhost:8083
#    ports:
#      - "4040:4040"

  backend:
    build: .
    container_name: backend
    ports:
      - 8083:8080
    restart: always
    depends_on:
      - db
#      - ngrok
#    networks:
#      - ngrok
#      - postgres

  frontend:
    build:
      context:  ./frontend
      dockerfile: Dockerfile
      args:
        PROXY_URL: http://backend:8080
    container_name: frontend
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - backend

#networks:
#  ngrok:
#  postgres:
