spring:
  application.name: rlp

  datasource:
    url: jdbc:postgresql://localhost:54321/tourist_advice_db?useSSL=false
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    properties.hibernate:
      temp.use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: none
    generate-ddl: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

telegram:
  bot:
    user.name: travel_helper_test_task_bot
    path:  https://8d60ac901295.ngrok.io
    token: bot1866539993:AAFFYZuPLVqp99Wpl0FRpNRLKjcuL2gixGE