spring:
  application.name: travel_helper_test_task_telegram_bot

  datasource:
    url: jdbc:postgresql://postgres_db:5432/tourist_advice_db?useSSL=false
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    properties.hibernate:
      temp.use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.PostgreSQL95Dialect
      jdbc.lob.non_contextual_creation: true
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: true

telegram:
  bot:
    user.name: travel_helper_test_task_bot
    token: 1866539993:AAFFYZuPLVqp99Wpl0FRpNRLKjcuL2gixGE
    webhook_register_root_url: https://api.telegram.org/bot${telegram.bot.token}/setWebhook

ngrok:
  url: http://ngrok:4551/api/tunnels/command_line
  created_url_parameter: public_url

server:
  port: 8081
